language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
env:
  global:
  - secure: TqPeV/7WDU01qn8jjYJkzJGnwREdjgkZCu5JW5HUnuh5Dfk89iEB8P2+hD6DnGdDQlrzBrPyvUuYRIF/cFsZIucbFTcbJXIm2YuHrSTP37UU+9N+hZd/sFNmQYjKhVhxSBysDfiCvIVgfLoxm93bWBMYCx37NRiT8WD9qCAKp1w=
  - secure: gguwvrGPPXUzMH0ygShVhk84iI3G/VHlT5OFPG/rN0RkGb383Xnvb7CSqwLWlDMINHCu3wSK3oAc69V5HYg/vfuRLX83I4GZQEzCVKZl0XqiVzvIfUFPO2TY0US2QkHUn1/F6bhSSKQPcqNlMvRxxfiKOMnlO7Ed2spYk1Qygfg=
addons:
  sauce_connect:
    username:
      secure: CYfKmsM4xS4AiqhTMqBMOQTaeRdESqisoPRIem2jJn6RbjKxK1Zs/3pNddla0NlZWM1NTGitWoQOprzjOOUBsARIeP4QD2Xfwr3RUfyzDhgaFDZ+gg1YkXlquh9ROmiEJnBIT6hWCEYMk67JAL2Bg4AluYgJco/cCRb85B7+eus=
    access_key:
      secure: A4w7g/KwXQY0gMh5c5aJoxrqLhvqgjndGrSNC7SO8MkXjYX/Oxr3ZdwWiar14fppQG20xpupgrOBAanRLDHJ81QB/Q7C1+w1QjJj3I48ekKB9T/5tv2o17m1wPGa4Vxbl9CX7Ovn4VNCyk5lqsRd3KqhL/QEvYP9H+jx0HCVw/0=
notifications:
  sqwiggle:
    secure: UeQ+71QnKxGZTvRErntn3lmKxE+zE57GEnWpWyTSG86rMytSfF/bY/oNMqP3ItlMeGA7xQmBD7fIL4iW+59u+X86HS/LtIiljBvrp//VuTZ/+KuT4zh6zALqQUD0wjIQ1SAHtXoxJZanRcJLIDZUZFrI4KeLqvH6aHcMwxBqUXc=
