language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
env:
  global:
  - secure: TqPeV/7WDU01qn8jjYJkzJGnwREdjgkZCu5JW5HUnuh5Dfk89iEB8P2+hD6DnGdDQlrzBrPyvUuYRIF/cFsZIucbFTcbJXIm2YuHrSTP37UU+9N+hZd/sFNmQYjKhVhxSBysDfiCvIVgfLoxm93bWBMYCx37NRiT8WD9qCAKp1w=
  - secure: gguwvrGPPXUzMH0ygShVhk84iI3G/VHlT5OFPG/rN0RkGb383Xnvb7CSqwLWlDMINHCu3wSK3oAc69V5HYg/vfuRLX83I4GZQEzCVKZl0XqiVzvIfUFPO2TY0US2QkHUn1/F6bhSSKQPcqNlMvRxxfiKOMnlO7Ed2spYk1Qygfg=
