language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli
- npm install -g codeclimate-test-reporter
after_script:
- cat coverage/lcov.info | codeclimate
env:
  global:
  - secure: TqPeV/7WDU01qn8jjYJkzJGnwREdjgkZCu5JW5HUnuh5Dfk89iEB8P2+hD6DnGdDQlrzBrPyvUuYRIF/cFsZIucbFTcbJXIm2YuHrSTP37UU+9N+hZd/sFNmQYjKhVhxSBysDfiCvIVgfLoxm93bWBMYCx37NRiT8WD9qCAKp1w=
  - secure: gguwvrGPPXUzMH0ygShVhk84iI3G/VHlT5OFPG/rN0RkGb383Xnvb7CSqwLWlDMINHCu3wSK3oAc69V5HYg/vfuRLX83I4GZQEzCVKZl0XqiVzvIfUFPO2TY0US2QkHUn1/F6bhSSKQPcqNlMvRxxfiKOMnlO7Ed2spYk1Qygfg=
  - secure: WHzsF6qGr049DUVORbgwjs5tV8OzLt4OnQehEpKTjhGa4EIIwm4MFpK525WDOCWW92p2nnSvqd1trd44bHsKXGcl87uX+V0CCRW5B1f4aRj54VBFo5+K3lEossM2a6Amqs4ZZDEJkmhHMHffMVEW3TFKlibF4BLp7CM5kUfcwYE=
addons:
  sauce_connect:
    username:
      secure: CYfKmsM4xS4AiqhTMqBMOQTaeRdESqisoPRIem2jJn6RbjKxK1Zs/3pNddla0NlZWM1NTGitWoQOprzjOOUBsARIeP4QD2Xfwr3RUfyzDhgaFDZ+gg1YkXlquh9ROmiEJnBIT6hWCEYMk67JAL2Bg4AluYgJco/cCRb85B7+eus=
    access_key:
      secure: A4w7g/KwXQY0gMh5c5aJoxrqLhvqgjndGrSNC7SO8MkXjYX/Oxr3ZdwWiar14fppQG20xpupgrOBAanRLDHJ81QB/Q7C1+w1QjJj3I48ekKB9T/5tv2o17m1wPGa4Vxbl9CX7Ovn4VNCyk5lqsRd3KqhL/QEvYP9H+jx0HCVw/0=
notifications:
  sqwiggle:
    secure: MdXm8Pu+VWs6o7rcvL65o1fTQX0HvicChCkAuddQLNpK0v64K5rtug53FTbXUUG09PIhlfKxE3lCk4TstpVolsOFDZboclg0qgfsnAKfqBVRaG5tAne6xcnFAxyh5xhthSAUIF1FBpxpOyDBeUv3Z2Yq9pG2WMetHRpSCHwFWzA=
deploy:
  provider: nodejitsu
  user: deiwin
  api_key:
    secure: aU1x3RVu1GaD1lwnhjPxXRYV/tZxyd90JyxXiMpAWrWK6EAyaaYupqS88Z7q0u35IgGw5ArrLy/MBPqpdTbEU0loa7bCZXMCNjuI3qtj2SUUY6r3fPiRBOHGHJ0E+s5KNhqes9YZOG7Tyc38huPv8SRhabTE/GU/GJR6E/21Ow8=
  on:
    repo: deiwin/praad
